# Haptique Extender - AUTOMATIONS
# Place this file in: /config/packages/haptique_extender_automation.yaml

# ============================================
# AUTOMATIONS
# ============================================

automation:
  # AUTO-REFRESH: Update command list on device change (REPLAY)
  - id: haptique_auto_update_commands_on_device_change
    alias: "Haptique - Auto Update Commands (Replay)"
    description: "Updates the command list when changing device in Replay"
    trigger:
      - platform: state
        entity_id: input_select.haptique_replay_device
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state not in ['No device available', 'Device 1', ''] }}"
    action:
      - service: script.haptique_update_command_list
    mode: single

  # AUTO-REFRESH: Update command list on device change (SERVICES DB)
  - id: haptique_auto_update_commands_services_db
    alias: "Haptique - Auto Update Commands (Services DB)"
    description: "Updates the command list when changing device in Services DB"
    trigger:
      - platform: state
        entity_id: input_select.haptique_services_device
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state not in ['Select a device', ''] }}"
    action:
      - service: script.haptique_update_services_command_list
    mode: single

  # AUTO-REFRESH: Refresh lists on Home Assistant startup
  - id: haptique_auto_refresh_on_startup
    alias: "Haptique - Auto Refresh on Startup"
    description: "Refreshes all device lists on HA startup"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: "00:00:20"  # Wait 20s for everything to initialize
      - service: script.haptique_update_device_list
      - service: script.haptique_update_all_services_lists
    mode: single

  # AUTO-REFRESH: Refresh after learning a command
  - id: haptique_auto_refresh_after_learn
    alias: "Haptique - Auto Refresh After Learning"
    description: "Refreshes lists after learning a new command"
    trigger:
      - platform: state
        entity_id: sensor.haptique_extender_last_learn_ir_code
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'unknown' and trigger.to_state.state != trigger.from_state.state }}"
    action:
      - delay: "00:00:02"  # Wait for DB to be updated
      - service: script.haptique_update_device_list
      - service: script.haptique_update_all_services_lists
    mode: single
